Implemented support for partials.
fenekku/moustachu pull request #7
Opened 2017-06-10 16:25 UTC by h3rald

This should fix #1.

2017-07-15 09:43 UTC, watzon commented
Anything holding this up @fenekku ?

2017-07-16 15:00 UTC, fenekku commented
> Anything holding this up @fenekku ?

Vacation mostly :), but also I think I never quite understood the "disk partials" use and use case which was why I didn't implement it if I recall. I implemented the "in-memory" partials however which made sense to me. 

I did it by not having an additional `partials` parameter because I didn't quite see the need for it - the API to make work in other implementations have always seemed clunky to me. Sure it would help to differentiate between a filename and a string but the computer can probably do it for you. The questions "is that a filename's path?" and "What is the relative location of that path?" just added more complexity. I wanted something simpler, but again it is probably because I never understood the full picture.  

Could you provide an example of file structure, templates, contexts and calls to illustrate the usage of disk partials? Once it makes sense I would be happy to merge!

2017-07-17 16:10 UTC, h3rald commented
Hi! 

Sure. I am currently building a small, self-contained static site generator ([hastysite](https://github.com/h3rald/hastysite)) in nim, and I am currently using mustache as templating engine.

I implemented partials support because I needed a way to reuse things like header, footer etc. in (potentially) several page-level templates. [Here](https://github.com/h3rald/min/tree/master/site/templates) you can find some example templates -- in particular the page.mustache template references the others. This is a pointless example because I only have one top-level template, but I could create others and reuse the same partials.

The actual render call within hastysite is [here](https://github.com/h3rald/hastysite/blob/master/hastysite.nim#L311). In this case, I am assuming that all templates will be within the same folder (let's say it's "good enough" for me).

2017-07-19 02:33 UTC, fenekku commented
Cool! 

Let me look into this/try this out because I also used partials for my personal static site generator (but clearly I didn't have 'disk partials'). I had the generator program read specific templates from disk and assign them to context variables which were then injected as partials. I had complete control this way.

2017-07-22 22:35 UTC, fenekku requested changes
Thanks for your contribution!

Once the comments are addressed I will merge this in.

2017-07-22 22:35 UTC, fenekku commented on src/moustachu.nim
> +  import os
Given that `os` is imported at the top of the file, we shouldn't have to import it again.

2017-07-22 22:35 UTC, fenekku commented on src/moustachu.nim
> +proc render(tmplate: string, contextStack: seq[Context], pwd="."): string =
Let's change `pwd` to `partials_dir` since the directory containing the partials files is not necessarily the present working directory.

2017-07-22 22:35 UTC, fenekku commented on src/moustachu.nim
> +      var partialTemplate = pwd.joinPath(token.value & ".mustache").readFile
I still like to be able to pass in-memory moustache strings in my context variables. And those should take precedence over disk partials.

We can have something like:

```nim
var partialTemplate = contextStack.lookupString(token.value)
if partialTemplate == "":
  partialTemplate = readFile(partials_dir.joinPath(token.value & ".mustache"))
```

2017-07-22 22:35 UTC, fenekku commented on src/moustachu.nim
> +  result = tmplate.render(contextStack, pwd)
`pwd` -> `partials_dir`

2017-07-22 22:35 UTC, fenekku commented on src/moustachu.nim
> +  var pwd = tmplateFilename.parentDir()
personal preference: `parentDir(tmplateFilename)` (or without the ending `()`)

2017-07-22 22:37 UTC, fenekku commented
Also don't forget to bump the version!

2017-08-04 17:21 UTC, h3rald commented
@fenekku Sorry for the delay -- I think I implemented the changes you requested, please take a look :)
I bumped the version to 0.11.0... not sure if you follow semantic versioning, but I thought that this could be considered a new feature rather than a bugfix after all, but again up to you!

2017-08-10 00:46 UTC, fenekku approved these changes
Thank you for your contribution @h3rald !

2017-08-10 00:47 UTC, merged